version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ../TaskManager
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://damianpolakovs2004:Damianba123@web2-2024.s3p8g.mongodb.net/?retryWrites=true&w=majority
      - DB_NAME=Web2-2024
      - PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
