services:
  - type: web
    name: grade-management-frontend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://taskmanager-api.onrender.com # This will be the URL of your backend
    autoDeploy: true
